import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting comprehensive database seed (24 hypercars & supercars)...');

  // Clean existing data
  await prisma.vehicle.deleteMany();
  await prisma.user.deleteMany();

  // Create Users
  const adminPassword = await bcrypt.hash('Megha_423', 10);
  const customerPassword = await bcrypt.hash('Megha_423', 10);

  const admin = await prisma.user.create({
    data: {
      name: 'Meghana K (Dealership Admin)',
      email: '23wh1a12c1@bvrithyderabad.edu.in',
      password: adminPassword,
      role: 'ADMIN',
    },
  });

  const customer = await prisma.user.create({
    data: {
      name: 'Meghana K (Customer)',
      email: 'kmegha9505@gmail.com',
      password: customerPassword,
      role: 'CUSTOMER',
    },
  });

  console.log(`👤 Created Users:
  - Admin: ${admin.email} (Password: Megha_423)
  - Customer: ${customer.email} (Password: Megha_423)`);

  // Create 24 Comprehensive Vehicles Set
  const vehicles = [
    {
      make: 'Koenigsegg',
      model: 'Jesko Attack',
      category: 'Hypercar',
      year: 2024,
      price: 3400000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 1600,
      zeroToSixty: '2.5s',
      topSpeed: '310 mph',
      isFeatured: true,
      description: '5.0-liter twin-turbo V8 producing 1,600 HP on E85 biofuel with 9-speed Light Speed Transmission.',
      imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Bugatti',
      model: 'Chiron Super Sport',
      category: 'Hypercar',
      year: 2024,
      price: 3800000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 1578,
      zeroToSixty: '2.2s',
      topSpeed: '273 mph',
      isFeatured: true,
      description: '8.0-liter quad-turbocharged W16 engine producing 1,578 horsepower with longtail aerodynamically optimized bodywork.',
      imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Pagani',
      model: 'Utopia V12',
      category: 'Hypercar',
      year: 2024,
      price: 2500000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 852,
      zeroToSixty: '2.8s',
      topSpeed: '230 mph',
      isFeatured: true,
      description: 'Handcrafted AMG 6.0L twin-turbo V12 mated to a 7-speed manual gated gearbox.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ferrari',
      model: 'SF90 XX Stradale',
      category: 'Supercar',
      year: 2024,
      price: 890000,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 1016,
      zeroToSixty: '2.3s',
      topSpeed: '199 mph',
      isFeatured: true,
      description: 'Plug-in hybrid V8 with 3 electric motors and fixed rear wing motorsport aerodynamics.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Tesla',
      model: 'Model S Plaid',
      category: 'Electric',
      year: 2024,
      price: 89990,
      quantity: 5,
      status: 'IN_STOCK',
      horsepower: 1020,
      zeroToSixty: '1.99s',
      topSpeed: '200 mph',
      isFeatured: true,
      description: 'Tri-motor All-Wheel Drive, carbon-sleeved rotors, 396 mile estimated range.',
      imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Porsche',
      model: 'Taycan Turbo GT',
      category: 'Electric',
      year: 2024,
      price: 230000,
      quantity: 3,
      status: 'IN_STOCK',
      horsepower: 1092,
      zeroToSixty: '2.1s',
      topSpeed: '180 mph',
      isFeatured: true,
      description: 'Weissach package lightweight electric track monster with Attack Mode boost.',
      imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'BMW',
      model: 'M4 Competition',
      category: 'Sports',
      year: 2024,
      price: 79100,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 503,
      zeroToSixty: '3.4s',
      topSpeed: '180 mph',
      isFeatured: true,
      description: '3.0L BMW M TwinPower Turbo inline 6-cylinder with M xDrive.',
      imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Porsche',
      model: '911 GT3 RS',
      category: 'Sports',
      year: 2024,
      price: 241300,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 518,
      zeroToSixty: '3.0s',
      topSpeed: '184 mph',
      isFeatured: true,
      description: 'Naturally aspirated 4.0-liter flat-six engine with active DRS motorsport aerodynamics.',
      imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ferrari',
      model: 'Purosangue V12',
      category: 'Luxury',
      year: 2025,
      price: 398350,
      quantity: 0,
      status: 'COMING_SOON',
      horsepower: 715,
      zeroToSixty: '3.3s',
      topSpeed: '193 mph',
      isFeatured: true,
      description: 'Naturally aspirated 6.5-liter V12 supercar SUV. Arriving Q4 2025.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'McLaren',
      model: '750S Spider',
      category: 'Supercar',
      year: 2024,
      price: 345000,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 740,
      zeroToSixty: '2.7s',
      topSpeed: '206 mph',
      isFeatured: true,
      description: '4.0-liter twin-turbo V8, ultralight carbon fiber Monocage II chassis with retractable hardtop roof.',
      imageUrl: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Maserati',
      model: 'MC20 Cielo Convertible',
      category: 'Convertible',
      year: 2024,
      price: 275000,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 621,
      zeroToSixty: '2.9s',
      topSpeed: '202 mph',
      isFeatured: false,
      description: 'Nettuno 3.0L twin-turbo V6 engine with electrochromic glass retractable roof.',
      imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Aston Martin',
      model: 'DB12 Volante',
      category: 'Convertible',
      year: 2024,
      price: 265000,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 671,
      zeroToSixty: '3.6s',
      topSpeed: '202 mph',
      isFeatured: false,
      description: '4.0-liter Twin-Turbo V8 producing 671 HP with K-fold roof mechanism and bespoke interior leather.',
      imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Lamborghini',
      model: 'Revuelto V12 Hybrid',
      category: 'Hypercar',
      year: 2024,
      price: 604000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 1001,
      zeroToSixty: '2.5s',
      topSpeed: '217 mph',
      isFeatured: true,
      description: '6.5L naturally aspirated V12 combined with 3 electric motors delivering 1,001 HP.',
      imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Lamborghini',
      model: 'Urus Performante',
      category: 'SUV',
      year: 2024,
      price: 269885,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 657,
      zeroToSixty: '3.1s',
      topSpeed: '190 mph',
      isFeatured: true,
      description: '4.0-liter twin-turbo V8 producing 657 horsepower, carbon fiber hood, Akrapovič titanium exhaust.',
      imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Audi',
      model: 'RS e-tron GT',
      category: 'Electric',
      year: 2024,
      price: 106500,
      quantity: 0,
      status: 'SOLD_OUT',
      horsepower: 637,
      zeroToSixty: '3.1s',
      topSpeed: '155 mph',
      isFeatured: false,
      description: 'Quattro all-wheel drive, 637 hp boost mode, carbon fiber roof package. Fully reserved.',
      imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Lucid',
      model: 'Air Sapphire',
      category: 'Electric',
      year: 2024,
      price: 249000,
      quantity: 3,
      status: 'IN_STOCK',
      horsepower: 1234,
      zeroToSixty: '1.89s',
      topSpeed: '205 mph',
      isFeatured: true,
      description: 'Three-motor powertrain delivering 1,234 hp, carbon ceramic brakes, track-tuned suspension.',
      imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Rolls-Royce',
      model: 'Spectre EV',
      category: 'Luxury',
      year: 2024,
      price: 420000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 577,
      zeroToSixty: '4.4s',
      topSpeed: '155 mph',
      isFeatured: true,
      description: 'The world first ultra-luxury electric super coupe with Starlight doors and Planar suspension.',
      imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Range Rover',
      model: 'SV Bespoke Edition',
      category: 'SUV',
      year: 2024,
      price: 234000,
      quantity: 3,
      status: 'IN_STOCK',
      horsepower: 606,
      zeroToSixty: '4.3s',
      topSpeed: '162 mph',
      isFeatured: false,
      description: '4.4-liter Twin-Turbo V8 with 24-way heated and cooled massaging front seats.',
      imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Chevrolet',
      model: 'Corvette Z06',
      category: 'Sports',
      year: 2024,
      price: 112700,
      quantity: 4,
      status: 'IN_STOCK',
      horsepower: 670,
      zeroToSixty: '2.6s',
      topSpeed: '195 mph',
      isFeatured: true,
      description: 'Mid-engine 5.5L LT6 flat-plane crank V8 revving to 8,600 RPM.',
      imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Cadillac',
      model: 'Escalade-V Series',
      category: 'SUV',
      year: 2024,
      price: 152295,
      quantity: 2,
      status: 'IN_STOCK',
      horsepower: 682,
      zeroToSixty: '4.4s',
      topSpeed: '125 mph',
      isFeatured: false,
      description: 'Hand-built 6.2L Supercharged V8 producing 682 HP with 38-inch curved OLED display.',
      imageUrl: 'https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Nissan',
      model: 'GT-R Nismo',
      category: 'Sports',
      year: 2024,
      price: 221090,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 600,
      zeroToSixty: '2.9s',
      topSpeed: '205 mph',
      isFeatured: false,
      description: '3.8L Twin-Turbo VR38DETT V8 with GT3 turbochargers and carbon-ceramic brakes.',
      imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Mercedes-AMG',
      model: 'G 63 Grand Edition',
      category: 'SUV',
      year: 2024,
      price: 179000,
      quantity: 1,
      status: 'LOW_STOCK',
      horsepower: 577,
      zeroToSixty: '4.5s',
      topSpeed: '149 mph',
      isFeatured: false,
      description: 'Handcrafted AMG 4.0L V8 biturbo engine with tech gold accents and matte black finish.',
      imageUrl: 'https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ford',
      model: 'F-150 Lightning',
      category: 'Truck',
      year: 2024,
      price: 54995,
      quantity: 8,
      status: 'IN_STOCK',
      horsepower: 580,
      zeroToSixty: '3.8s',
      topSpeed: '110 mph',
      isFeatured: false,
      description: 'All-electric pickup truck with dual motors, extended range battery, Pro Power Onboard.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Toyota',
      model: 'GR Supra 3.0',
      category: 'Sports',
      year: 2024,
      price: 58500,
      quantity: 6,
      status: 'IN_STOCK',
      horsepower: 382,
      zeroToSixty: '3.9s',
      topSpeed: '155 mph',
      isFeatured: false,
      description: '3.0L turbocharged inline 6-cylinder with 6-speed intelligent Manual Transmission (iMT).',
      imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    },
  ];

  for (const v of vehicles) {
    await prisma.vehicle.create({ data: v });
  }

  console.log(`🚗 Seeded ${vehicles.length} rich vehicles into inventory.`);
  console.log('✅ Database seeding finished successfully.');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
